### ISSUE TITLE
Its not really an issue

### ISSUE THREAD

**Issue by Tomato6966** [adasq/dropbox-v2-api#1119]
So i managed to upload a file via nodejs

But i don't know how to use the result, to get a share link to automatically send it somewhere.

Could u please help me?

```javascript
const dropboxV2Api = require('dropbox-v2-api');
      // create session ref:
      const dropbox = dropboxV2Api.authenticate({
        token: 'XXX'
      });
     // use session ref to call API, i.e.:

dropbox({
  resource: 'files/upload',
  parameters: {
      path: '/dropbox/path/to/myvideo.mp4'
  },
  readStream: fs.createReadStream('./myvideo.mp4')
}, (err, result, response) => {
  if (err) { return console.log(err); }
  console.log(result);
})
```

**Comment by adasq** [comment]
Hey. After uploading file you have to call another endpoint in order to set it public:
https://github.com/adasq/dropbox-v2-api/blob/master/EXAMPLES.md#sharingcreate_shared_link_with_settings-see-docs
More about request/response on officialdocs:
https://www.dropbox.com/developers/documentation/http/documentation#sharing-create_shared_link_with_settings

**Comment by Tomato6966** [comment]
Thank you v ery much, especially for that fast answer it worked!!!
